feat: save selected asset send/receive into localstorage
BoltzExchange/boltz-web-app pull request #288
Opened 2023-10-16 14:23 UTC by dni

2023-10-16 20:59 UTC, michael1011 approved these changes

2023-10-16 20:59 UTC, michael1011 commented
Closes #286

2023-10-16 21:00 UTC, michael1011 requested changes
![image](https://github.com/BoltzExchange/boltz-web-app/assets/8138838/3c5cc3e8-e1d4-4181-9558-6b28cfd8e99f)

Does not work; when liquid is selected the fee for mainchain is still shown and used

2023-10-17 16:55 UTC, michael1011 approved these changes

2023-10-17 17:14 UTC, kilrau approved these changes
LGTM

2023-10-17 17:15 UTC, merged