feat: add bip21 addresses for onchain and lightning
BoltzExchange/boltz-web-app pull request #304
Opened 2023-11-13 22:32 UTC by dni

closes #302

2023-11-14 21:23 UTC, michael1011 requested changes

2023-11-14 21:23 UTC, michael1011 commented on src/utils/invoice.js
> +export function trimPrefix(invoice, prefix) {
Horrible function name. Something like `extractBip21Address` would be better

2023-11-14 21:23 UTC, michael1011 commented on src/utils/invoice.js
> +export function trimBip21Lightning(invoice) {
Same here. `extractBip21Invoice`

2023-11-14 21:23 UTC, michael1011 commented on src/utils/invoice.js
> +        return url.pathname;
And there is no test making sure the URL query parameters of the `invoice` variable are removed

2023-11-16 12:41 UTC, kilrau requested changes
Reverse Swap BIP21 works with segwit addresses:
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/7656286e-f654-4be5-8b8e-b69216bc5a56)

But not with nested or legacy:
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/6d7e9889-92ff-49fb-b426-c83d13b2c36c)
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/b3a3bf07-b787-49a0-a82e-2e3856a997ab)

![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/7fc7c740-768e-4e0b-817f-179ab2c092ef)

2023-11-16 12:50 UTC, kilrau commented
Reverse swap works, but don't truncate, just leave the whole BIP21 unified string there just like you do for normal swaps.

Also make sure that tests cover it all.

2023-11-17 17:14 UTC, kilrau requested changes
Parsing unified BIP21s (https://bitcoinqr.dev/) for normal swaps works fine.

Reverse swaps still several issues:
* `liquidnetwork:` bip21s are not recognized
* `bitcoin:` with legacy P2PKH (1...) or P2WPKH-nested-in-P2SH (3...) still not recognized as I mentioned in my previous review.

2023-11-18 12:13 UTC, dni commented
waiting for other prs to resolve first

2023-12-07 09:27 UTC, closed without merging