fix: issue 281, timeout_blockheight
BoltzExchange/boltz-web-app pull request #309
Opened 2023-11-16 10:12 UTC by dni

closes #281

before:
![screenshot-1700129441](https://github.com/BoltzExchange/boltz-web-app/assets/1743657/2bbcf7e2-c917-4095-bcd8-7e15b3e243cb)

after:
![screenshot-1700129441](https://github.com/BoltzExchange/boltz-web-app/assets/1743657/72ad6d20-9612-40e7-a76a-42f9078504ba)

2023-11-16 12:23 UTC, kilrau commented
Can we:
- adjust `btc` denomination to `L-BTC` or `RBTC` or `BTC` depending on swap type
- move `Send 0.001X ...` on top of QR Code
- below address box `Make sure your transaction confirms within {invoice expiry|swapexpiry} hours!

2023-11-17 16:18 UTC, kilrau approved these changes

2023-11-17 18:00 UTC, kilrau requested changes
Normal Swap shoulds say `sats` if denomination is sats, L-BTC if denomination is full BTC
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/604384e2-4036-4153-8350-71eda4771b58)

Reverse Swap should say `sats` (plural), L-BTC if denomination is full BTC
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/875e6090-2987-4a75-9b38-9963fa2fb64f)

2023-11-18 13:50 UTC, michael1011 requested changes
The sats denomination should say sats

@kilrau check the updated i18n strings

2023-11-18 13:50 UTC, michael1011 commented on src/status/SwapCreated.jsx
> +                <hr />
I don't like this hr

2023-11-18 13:51 UTC, michael1011 commented on src/helper.js
> +    return str.substring(0, 20) + "..." + str.substring(str.length - 20);
```suggestion
    return str.substring(0, 19) + "..." + str.substring(str.length - 19);
```

Else it won't fit in one line

![image](https://github.com/BoltzExchange/boltz-web-app/assets/8138838/9d6eecfa-1f67-4a41-9203-f856804a234e)

2023-11-18 23:12 UTC, dni commented
should now say sats, and also the according assets if denom btc and not an lightingpayment

2023-11-19 20:26 UTC, michael1011 approved these changes

2023-11-19 20:26 UTC, merged