feat: add qrscanner for addresses and invoices
BoltzExchange/boltz-web-app pull request #323
Opened 2023-11-18 13:28 UTC by dni

WIP

2023-12-07 12:18 UTC, kilrau commented
- remove scan qr code button if not mobile
- when I do a reverse swap to mainchain but scan a liquid address qr it doesn't paste nor give me an error

2023-12-13 22:02 UTC, michael1011 requested changes
Scanned onchain addresses are set but not validated

2023-12-13 22:02 UTC, michael1011 commented on src/Create.jsx
> +            <QrScan />
You should do the mobile check here

2023-12-19 08:36 UTC, dni commented on src/Create.jsx
> +            <QrScan />
done

2023-12-19 13:10 UTC, michael1011 requested changes
Clicking the image to close the QR code scanner without actually scanning a QR code is unintuitive. Keep the behaviour but put an X icon in some corner

2023-12-20 07:01 UTC, dni commented
> Clicking the image to close the QR code scanner without actually scanning a QR code is unintuitive. Keep the behaviour but put an X icon in some corner

fixed

2024-01-03 10:24 UTC, kilrau requested changes
Can you rebase this branch? Looks like this has an address validation bug

![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/c0e8d3cb-9812-41e4-b4bc-3589d689a0c9)

2024-01-03 20:01 UTC, michael1011 commented
> Can you rebase this branch? Looks like this has an address validation bug

are you on the right network?

2024-01-03 20:07 UTC, merged