feat: extract from bip21 follow up
BoltzExchange/boltz-web-app pull request #349
Opened 2023-12-07 09:27 UTC by dni

closes #302
closes #304 

- added `liquidnetwork:`

2023-12-07 10:57 UTC, kilrau requested changes
see comment above

2023-12-07 12:36 UTC, kilrau approved these changes
Yup, now behaves as expected. LGTM

2023-12-07 13:30 UTC, michael1011 commented on src/utils/invoice.ts
> +export const liquidPrefix = "liquidnetwork:";
`liquidtestnet` for testnet

2023-12-07 13:33 UTC, michael1011 requested changes

2023-12-07 13:33 UTC, michael1011 commented on src/utils/invoice.ts
> +    return data.startsWith(bitcoinPrefix) || data.startsWith(liquidPrefix);
This is case sensitive. Is that fine? Do any wallets put the prefix in uppercase?
Let's make this not case sensitive just in case

2023-12-07 13:34 UTC, michael1011 requested changes
![image](https://github.com/BoltzExchange/boltz-web-app/assets/8138838/198d6c4b-474f-42e1-b291-cd7327424a21)

When entering bip21 first, the button shows an error. But the address is valid. Error goes away as soon as the amounts are changed

2023-12-13 18:14 UTC, michael1011 requested changes
![image](https://github.com/BoltzExchange/boltz-web-app/assets/8138838/a19b9c9e-3aa2-4954-a6fe-d223a152a88e)

Prefixes of invoices are not removed before sending them to the backend

2023-12-13 19:35 UTC, michael1011 approved these changes

2023-12-13 19:35 UTC, merged