fix: translage create button label on change
BoltzExchange/boltz-web-app pull request #364
Opened 2023-12-13 21:30 UTC by dni

closes #363

2023-12-14 11:25 UTC, michael1011 requested changes

2023-12-14 11:25 UTC, michael1011 commented on src/components/CreateButton.tsx
> +    };
Do not do this here. Label and arguments should be set together

2023-12-14 12:20 UTC, kilrau requested changes
Still found some cases like this one where language is not switched:
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/b4d2b3a5-d916-485d-b800-11a7af2a5c65)

2023-12-14 16:18 UTC, michael1011 commented on src/Create.jsx
>              setCustomValidity(errorMsg, amount === 0);
What does `setCustomValidity` even do and why does it needs text? I've never seen it displayed before

2023-12-14 17:35 UTC, dni commented on src/Create.jsx
>              setCustomValidity(errorMsg, amount === 0);
its the html5 input validition error when you mouse over

2023-12-15 11:27 UTC, kilrau approved these changes

2023-12-18 14:20 UTC, merged