fix: assets depends on config settings
BoltzExchange/boltz-web-app pull request #369
Opened 2023-12-14 13:11 UTC by dni

now asset select will actually use assets configured on config.js

2023-12-14 13:14 UTC, kilrau requested changes
Works on mainnet, on testnet it still happens (see url, it's the testnet deployment from this branch)

![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/ae272e33-feb3-4076-9a3d-33cecb80f936)

2023-12-14 16:00 UTC, michael1011 requested changes

2023-12-14 16:00 UTC, michael1011 commented on src/context/Web3.tsx
> +            setHasMetamask(false);
Don't abuse the `hasMetamask` signal to check if RSK is available

2023-12-14 16:00 UTC, michael1011 commented on src/components/AssetSelect.jsx
> +    };
Why is this a function? It does only ever need to be evaluated once. Configs don't do reactive changes.

2023-12-14 16:00 UTC, michael1011 commented on src/components/AssetSelect.jsx
> +    };
Why is this a function? It does only ever need to be evaluated once. Configs don't do reactive changes.

2023-12-15 09:35 UTC, michael1011 approved these changes

2023-12-15 11:26 UTC, kilrau requested changes
Can you rebase this on master so the `C.json` fix is in and I can give this another proper test? @dni

2023-12-18 08:01 UTC, dni commented
rebased

2023-12-18 14:42 UTC, michael1011 approved these changes

2023-12-18 14:43 UTC, merged