feat: deeplinks for wallets
BoltzExchange/boltz-web-app pull request #378
Opened 2023-12-20 12:37 UTC by dni

add links on SwapCreated and InvoiceSet on the QR code and as button.

its working for alby on browser for me i did not test bip21 yet.

closes #299

![screenshot-1703075559](https://github.com/BoltzExchange/boltz-web-app/assets/1743657/3e89593c-e6a1-4e16-b1bf-fd8c37c1daa2)

i replaced the copy bip21 for the open in wallet button, usually you don't really want to copy bip21 right? else we get a small ui issue because we have to less room to make it look good.

![screenshot-1703075815](https://github.com/BoltzExchange/boltz-web-app/assets/1743657/e44f09ef-2932-4f01-b12b-c1c283d6926a)

2024-01-09 15:36 UTC, kilrau requested changes
Desktop:
- [ ] For Reverse Swaps on I don't think it makes sense to have the "Open in Wallet" button. It opens Alby, which already has the `Pay invoice via WebLN` button. https://github.com/LN-Zap/zap-desktop is archived, I don't think there is any other popular desktop lightning wallets that could make use of that button.
- [ ] For Normal Swaps, on my ubuntu system the handler couldn't find my Green wallet to open `liquidnetwork:`, I openen an [issue on green](https://github.com/Blockstream/green_qt/issues/103) side. For bitcoin mainchain the handler listed others
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/5da03504-c55e-463b-9a73-79d6404a0a5d) but then send dialogue and amounts couldn't be prefilled.

Summary: not very useful on Desktop, if you insist let's keep it for normal swaps only and we hope that Green & other wallets improve in future. I am also fine removing it completely for desktop.

Mobile:
Works beautifully in all wallets I tested. Everything prefilled as it should be, even in Green.

2024-01-10 16:37 UTC, kilrau requested changes
Reverse Swaps:
- [ ] So now `Pay invoice via WebLN` only applies to Desktop, `Open in Wallet` only applies for Mobile. I think we should unify style! Blue button on top vs both yellow next to each other. Don't care which, but it should be the same. `Scan QR Code` on mobile is blue on top, same style as `Pay invoice via WebLN` on Desktop.
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/d8496cbf-8fde-4e2f-a5c7-452817c6eeba)
![Screenshot from 2024-01-10 17-19-55](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/346a9243-7d33-47e2-a04d-85d7d2c1db6a)

Normal Swaps:
- [x] Mobile is missing `Copy Address` now. Which is only acceptable if we add a copy symbol into the address filed so it's discoverable that the address can be copied by tapping on it. I just really don't like that there are 3 equally looking buttons on mobile and desktop doing different things.
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/a097310f-4814-49ff-ae86-adfa6ec47bff)
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/f6c371bb-5fe2-4b22-984e-20d9a6885b6a)

The "blue button on top" style for `Open in Wallet` can work if you agree doing https://github.com/BoltzExchange/boltz-web-app/issues/444

2024-01-11 17:39 UTC, kilrau commented
Since we are now free to do https://github.com/BoltzExchange/boltz-web-app/issues/444, we can use this button style for "open in wallet" on mobile.
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/e91c157d-94ea-4229-8078-fe55ecb3d006)

2024-01-23 12:28 UTC, dni commented
closes #444

2024-01-23 13:12 UTC, kilrau approved these changes

2024-01-23 13:14 UTC, merged