feat: disable webln create invoice button on invalid amount
BoltzExchange/boltz-web-app pull request #479
Opened 2024-02-12 10:07 UTC by dni

closes #380

2024-02-12 10:14 UTC, michael1011 requested changes

2024-02-12 10:14 UTC, michael1011 commented on src/components/WeblnButton.tsx
> +        <Show when={webln()}>
Components themselves should not decide if they are rendered. The parent does that

2024-02-12 10:14 UTC, michael1011 commented on src/components/WeblnButton.tsx
> +            <hr class="spacer" />
Same for the surrounding styling

2024-02-12 10:14 UTC, michael1011 commented on tests/components/WeblnButton.spec.tsx
> +describe("WeblnButton", () => {
Also test the disabling logic

2024-02-12 18:28 UTC, kilrau requested changes
- didn't you want to leave it enabled for the default empty state because [one can type amounts](https://github.com/BoltzExchange/boltz-web-app/issues/380#issuecomment-1921466443) ?
- if amount is not default empty, "out of min/max" error should have prio over invoice error
![Screenshot from 2024-02-12 19-25-38](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/30342242-2ca3-4a89-ad79-a0aba3332392)

2024-02-13 07:47 UTC, dni commented
> didn't you want to leave it enabled for the default empty state because

it is enabled when amount are empty

2024-02-13 09:41 UTC, kilrau commented
> > didn't you want to leave it enabled for the default empty state because
> 
> it is enabled when amount are empty

No it isn't.

![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/48cd1d47-8a42-4885-a5be-d78b6e1fd962)

2024-02-13 09:45 UTC, kilrau commented
> * if amount is not default empty, "out of min/max" error should have prio over invoice error

still not fixed
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/36b7d7da-5340-4b30-8a3a-b508c357ee48)

2024-02-15 19:56 UTC, merged