feat: Implement Satscomma Formatting for Sats Amounts
BoltzExchange/boltz-web-app pull request #494
Opened 2024-02-28 22:30 UTC by thelmuxkriovar

**Description:**

This PR introduces the satcomma standard for formatting sats amounts. You can read [Bitcoin Magazine's 2021 article](https://bitcoinmagazine.com/culture/satcomma-standard-look-at-bitcoin-this) on the subject if you're not familiar with it.

The satcomma standard promotes readability and clarity when dealing with satoshis, by inserting a separator such as spaces or commas every three digits, starting from the decimal point for BTC values or from the least significant digit for satoshi amounts.

**Reasoning:**

- **User Experience**: Improving the way sats amounts are displayed can enhance the user experience, making it easier for users to verify amounts at a glance without counting digits
- **Standardization** - Satscomma is a standard recommended by [bitcoin.design](https://bitcoin.design/guide/designing-products/units-and-symbols/#satcomma)
- **Future-Proof**: As Bitcoin's adoption grows, and transactions in satoshis become more common, having a clear and consistent formatting standard will become increasingly important.

2024-03-05 21:46 UTC, michael1011 approved these changes
LGTM! Thank you for your contribution!

One minor change and running `npm run prettier` and this should be good to merge

2024-03-05 21:46 UTC, michael1011 commented on src/utils/denomination.ts
> +function satsComma(sats: string): string {
Could you an arrow function here?

2024-03-06 15:54 UTC, kilrau requested changes
Thank you so much for you contribution! This actually closes an issue which I attached to this PR: https://github.com/BoltzExchange/boltz-web-app/issues/146 :100: 

Tested, looks good! Tests need a fix, then good to go!

2024-03-06 16:45 UTC, dannym-arx commented on tests/utils/denomination.spec.ts
> -            ${denominations.sat} | ${"12312300000"}        | ${false}
not sure why this was false before, but it's a valid amount, `12 312 300 000 sats` or `123.12300000 btc`

2024-03-06 17:51 UTC, michael1011 commented on tests/utils/denomination.spec.ts
> -            ${denominations.sat} | ${"12312300000"}        | ${false}
You increased the number of digits: https://github.com/BoltzExchange/boltz-web-app/pull/494/files#diff-dc22175eeda6fbd73202ad7b56a3ad1122f4e277d858d8950e2ddf90655ff6c4R90

2024-03-07 13:33 UTC, kilrau commented on tests/utils/denomination.spec.ts
> -            ${denominations.sat} | ${"12312300000"}        | ${false}
Revert this change and you should be good

2024-03-07 13:46 UTC, dannym-arx commented on tests/utils/denomination.spec.ts
> -            ${denominations.sat} | ${"12312300000"}        | ${false}
the current limit on boltz.exchange is 25 027 567, if I revert the change with the number of characters you wouldn't be able to enter that number anymore because it would be filtered out by the regex. 

I guess I could make a change to only count digits ignoring spaces, would that be acceptable?

2024-03-08 08:04 UTC, dni commented
just as a reference is tried something similar here, https://github.com/BoltzExchange/boltz-web-app/pull/165

2024-03-08 10:17 UTC, kilrau commented
Can you run prettier again? CI still complaining... @thelmuxkriovar 

![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/09d7b67c-8800-4796-acb1-cd83e4d82009)

PS: Replacing one or multiple (mark) numbers in the middle of a satcomma formatted amount makes the cursor jump to the very right. This is an acceptable trade-off imo, https://github.com/BoltzExchange/boltz-web-app/pull/165 tried to fix these edge cases and ended up being overly complicated and buggy.

2024-03-08 10:31 UTC, dni commented on tests/utils/denomination.spec.ts
> +            ${denominations.sat} | ${6}   | ${1000}
this should be 5 digits `1 000` some goes for following tests

2024-03-08 11:54 UTC, kilrau approved these changes

2024-03-08 13:08 UTC, dni approved these changes
LGTM! thanks!

2024-03-08 13:20 UTC, michael1011 approved these changes
We took the liberty of wrapping up the PR

Thank you!

2024-03-08 13:21 UTC, merged

2024-03-08 14:09 UTC, kilrau commented
> Awesome, sorry I haven't been very responsive I've been taking this week a bit slowly coding wise :)

Not at all, this was pretty smooth and we are planning to tag a release and deploy this soon!

Btw what motivated you to throw up this PR? Are you a Boltz Web App user and were missing this feature?

2024-03-08 15:01 UTC, kilrau commented
Very nice! Any other issue or feature you would want to work on in exchange for some sats - hmu (my handle is the same on all major platforms)!