fix: bail validation and refactor create button labels
BoltzExchange/boltz-web-app pull request #500
Opened 2024-03-11 13:19 UTC by dni

- button label is now way easier to work with
- validation only happens if there is a amount set at all

2024-03-11 15:37 UTC, michael1011 requested changes
There are no tests

2024-03-11 15:37 UTC, michael1011 commented on src/components/CreateButton.tsx
> +                } else {
No need for else if you always return in the previous `if`s

2024-03-11 15:37 UTC, michael1011 commented on src/components/CreateButton.tsx
> +            disabled={buttonDisable()}
![image](https://github.com/BoltzExchange/boltz-web-app/assets/8138838/2c9b9211-1f5a-4626-bb59-88b690b6828d)
Invoices of the wrong network have a yellow button that can't be clicked. How about setting the class of the button when the disabled status is changed?

2024-03-13 07:50 UTC, dni commented
closes #443

2024-03-13 07:54 UTC, dni commented
closes #353

2024-03-15 14:19 UTC, michael1011 approved these changes

2024-03-15 14:19 UTC, michael1011 commented on tests/components/CreateButton.spec.tsx
> +        expect(btn.disabled).toBeTruthy();
Let's also assert the text changed to address invalid

2024-03-15 14:51 UTC, kilrau requested changes
https://github.com/BoltzExchange/boltz-web-app/issues/443 seems to be fixed, couldn't get web app to resolve my lightning address with invalid/empty amounts

https://github.com/BoltzExchange/boltz-web-app/issues/353 for empty amounts the "Please provide a valid LN invoice, LNAddress or LNURL" should be shown too if I enter sth invalid: 
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/e5461e7b-406d-424e-8539-cee855c15908)
Same for Normal Swaps with empty amounts, it should show "Invalid BTC address"
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/a682a83c-ea3b-4b1f-8418-6a534ae9d277)

2024-03-18 15:06 UTC, kilrau requested changes
Let's fix error prios:
- let's stick with "Minimum amount is" as default state when loading the page, just as current master. But NEVER circle invoice/address field red if it's empty. Only when it's an invalid lnurl/lnaddress format. Grey button with error message is clear enough. Yes WebLN can be used to paste an invoice with amount and users will click the button if it's there even though the message says enter an amount. Accepted edge case trade-off.
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/adb5899f-b363-4ec5-a60e-b644046c4a6f)
- amount error supersedes all other errors, wrong ln address/lnurl show only if valid amount is set, test: amount error stays when I enter wrong lnurl/address
- invoice errors like 0 amount can show as-is as they are popups
- re-run amount validation when I manipulate amounts that passed validation before
- re-run lnurl/lnaddress/invoice/address validationwhen I manipulate an input that passed validation before

2024-03-19 10:46 UTC, kilrau requested changes
One minor things left:

- [ ] you are still showing red if the address input field is empty. Please show grey in case it's empty. Shouldn't have an error state if I'm just done punching in amounts
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/d2fa2fa7-7e98-40ce-9b00-96b7545f8fe4)

2024-03-19 16:29 UTC, kilrau approved these changes
LGTM

2024-03-19 22:34 UTC, michael1011 approved these changes

2024-03-19 22:35 UTC, merged