feat: add browser notification
BoltzExchange/boltz-web-app pull request #528
Opened 2024-03-22 08:20 UTC by dni

used when a swap is claimed or refunded.
initially tries to enable notfication but wont popup because it needs user permission. added one ask a create swap click and one on refund. could be added to amount input or address input aswell but needs a userevent to popup

2024-03-30 17:21 UTC, kilrau requested changes
I open the landing page and it immediately asks for notification permissions - NO
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/9bed055f-2aa1-491b-8e87-680d3251d596)

Then again on "Create Swap"... 

Please read the issue again! We only want notification permissions *if user toggles 0-conf off*: https://github.com/BoltzExchange/boltz-web-app/issues/346 so that should be the trigger.

2024-05-15 09:58 UTC, kilrau commented
As our testing just revealed: browser notification is "in your face" on page load, only should be triggered on toggle

2024-05-22 09:21 UTC, kilrau commented
In your face permission request gone, please resolve conflicts and request review, I'll do some e2e testing @dni

2024-05-22 11:33 UTC, kilrau requested changes
- need to gracefully handle incognito window
[Screencast from 2024-05-22 13-26-16.webm](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/2ca3be57-952a-4a52-b67a-6841d7055a75)
- didn't get any notification when I was in a different tab while the swap completed even though notifications were turned on

Tested in FF & Chromium.

2024-05-22 13:45 UTC, kilrau commented
Edge case but if the fix is easy let's please do it: if I withdraw notification permissions while switch is on, it's still on after reload. Reload should check permissions I guess.

[Screencast from 2024-05-22 15-43-46.webm](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/5b65001e-0af9-4f20-b01f-a4e83595a719)

2024-05-22 14:40 UTC, kilrau requested changes
We fixed a couple of things in my regtest setup and notfications are working now.

TODOs:

1. what I mentioned [above](https://github.com/BoltzExchange/boltz-web-app/pull/528#issuecomment-2124840924):
- if user clicks "block" on initial permission request
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/b6419e51-4948-4c93-94e1-d6b2472ca4a5)
- OR user is in incognito window
[Screencast from 2024-05-22 16-33-12.webm](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/ba3ec599-7aae-4127-9c90-4047668a67d8)
Both resulting in permissions not granted, let's throw "Notification permissions not granted." error when user tries to enable here. Right now just nothing happens when trying to enable notifications in these states.

2. Notifications for all failed swaps, right now it seems there are no notifications for failed swap states:
![Screenshot from 2024-05-22 16-37-05](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/90c828b3-2abd-4746-aad1-2d12b5c61c0f)

2024-05-23 10:11 UTC, kilrau approved these changes
Previous review was addressed, tested in FF&Chromium and works as expected. Strings fixed.

2024-05-23 11:54 UTC, michael1011 requested changes

2024-05-23 11:54 UTC, michael1011 commented on src/utils/notification.ts
> +    return new Promise((resolve) => {
```suggestion
    return new Promise<boolean>((resolve) => {
```

2024-05-23 11:54 UTC, michael1011 commented on src/components/RefundButton.tsx
> +            notify("success", t("refunded"), true, true);
No notifications on refunds. Those are direct actions after clicking a button

2024-05-23 11:54 UTC, michael1011 commented on src/components/BrowserNotification.tsx
> +        // if its false we try to enable it
```suggestion
        // When disabled, we try to request permission and enable them
```

2024-05-23 11:54 UTC, michael1011 commented on src/components/BrowserNotification.tsx
> +        // if its true we disable it
```suggestion
        // When enabled, we disable sending them
```

2024-05-23 11:54 UTC, michael1011 commented on src/context/Global.tsx
> +    // browser notification
```suggestion
```

2024-05-23 11:54 UTC, michael1011 commented on tests/setup.ts
> +    requestPermission: () => new Promise(() => jest.fn()),
```suggestion
    requestPermission: jest.fn().mockResolvedValue(true),
```

2024-05-23 13:13 UTC, kilrau commented
> 2\. Notifications for all failed swaps, right now it seems there are no notifications for failed swap states:

Did you add notifications for failed swaps? I broke my regtest again and can't test rn.

2024-05-23 13:29 UTC, kilrau commented
> 2\. Notifications for all failed swaps, right now it seems there are no notifications for failed swap states:

Moved into separate issue https://github.com/BoltzExchange/boltz-web-app/issues/601, from my side ok to merge this without

2024-05-23 14:29 UTC, michael1011 approved these changes

2024-05-23 14:29 UTC, michael1011 commented on src/i18n/i18n.ts
> +        notification_header: "Boltz Swap",
```suggestion
        notification_header: "Boltz",
```
I'd call this just Boltz. It's cleaner

2024-05-23 15:19 UTC, kilrau commented on src/i18n/i18n.ts
> +        notification_header: "Boltz Swap",
Cleaned. For all languages.

2024-05-23 15:20 UTC, merged