feat: play sound on successful swaps
BoltzExchange/boltz-web-app pull request #536
Opened 2024-03-27 08:47 UTC by dni

PoC :D still a random sound. but it could be played when wo do the notifications aswell. like here: https://github.com/BoltzExchange/boltz-web-app/pull/528

closes #338

2024-03-30 17:23 UTC, kilrau commented
Nice, but it should play independently from notifications, just like mempool.space

2024-05-06 10:23 UTC, kilrau commented
Don't have "Play sound". Just play it when one enables it via the toggle.

Also, please try a toggle style without writing "on/off" out. Or at least only one of them. These toggles were invented to signify on/off...

Also on right, off left seems to be standard these days

[![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/73c0e1a7-b)1da0-4a7d-a8a7-cf12d79d01db)
](https://www.google.com/search?q=on+off+toggle+switch+phone&tbm=isch&ved=2ahUKEwjSgMn65viFAxU9U6QEHehIDW0Q2-cCegQIABAA&oq=on+off+toggle+switch+phone&gs_lp=EgNpbWciGm9uIG9mZiB0b2dnbGUgc3dpdGNoIHBob25lSO0RULkGWMIOcAB4AJABAJgBUKABiQSqAQE3uAEDyAEA-AEBigILZ3dzLXdpei1pbWfCAgoQABiABBhDGIoFwgIFEAAYgATCAgYQABgHGB7CAgQQABgewgIGEAAYCBgewgIHEAAYgAQYGIgGAQ&sclient=img&ei=Mq84ZtKfNr2mkdUP6JG16AY&bih=1578&biw=1536&client=ubuntu-chr&hs=THf)

2024-05-17 06:29 UTC, michael1011 requested changes

2024-05-17 06:29 UTC, michael1011 commented on src/components/Audio.tsx
> +const Audio = () => {
```suggestion
const Audio = () => {
```

Give this a proper name. Like `SwapSuccessSoundSetting`

2024-05-17 06:29 UTC, michael1011 commented on src/components/RefundButton.tsx
> +            if (audio()) playSound();
I don't think that we should play a sound on refund

2024-05-17 06:29 UTC, michael1011 commented on src/context/Global.tsx
> +    const [audio, setAudio] = createSignal<boolean>(false);
```suggestion
    const [swapSuccessSound, setSwapSuccessSound = createSignal<boolean>(false);
```

This should be a persistent signal

2024-05-17 06:29 UTC, michael1011 commented on src/context/Global.tsx
> +    const playSound = () => {
```suggestion
    const swapSuccessSound = () => {
```

2024-05-17 06:29 UTC, michael1011 commented on src/context/Global.tsx
> +        const audio = new Audio("/sound.mp3");
Give the mp3 a proper file name too. Like eg `swapSuccessSound.mp3`

2024-05-17 06:29 UTC, michael1011 commented on src/i18n/i18n.ts
> +        enable_audio: "Enable Audio",
@kilrau check translations

2024-05-17 07:48 UTC, michael1011 requested changes

2024-05-17 07:48 UTC, michael1011 commented on src/context/Global.tsx
> +        createSignal<boolean>(false);
This needs to be persistent in local storage

2024-05-17 07:48 UTC, michael1011 commented on src/context/Global.tsx
> +    const notify = (type: string, message: string, audio?: boolean) => {
```suggestion
    const notify = (type: string, message: string, audio: boolean = false) => {
```

2024-05-22 09:55 UTC, kilrau commented
translations look good

2024-05-22 10:38 UTC, michael1011 approved these changes

2024-05-22 10:39 UTC, merged