feat: improve embedding of swapbox
BoltzExchange/boltz-web-app pull request #547
Opened 2024-03-31 07:12 UTC by dni

closes #334

adds invoice, address, asset, sendAmount, receiveAmount

2024-07-16 13:36 UTC, kilrau commented
Shall we push this one over the finish line? We recently had an integration that wanted "a simplified webview with prefilled swap data"

2024-08-13 08:17 UTC, dni commented
created an example embed page http://localhost:5174/boltz-webapp-embed/

2024-08-13 12:19 UTC, tohrxyz commented
really looking forward to this merging to main, because it's one of the fundamental parts that our project needs right now! :)

2024-08-13 20:00 UTC, kilrau requested changes
- `setInvoice` / `setAddress` -> `setDestination`
- `assetSend` / `assetReceive` -> `sendAsset` / `receiveAsset` to bring naming in line

2024-08-13 20:25 UTC, michael1011 requested changes
All URL query params we want people to use need to be documented

2024-08-13 20:25 UTC, michael1011 commented on src/context/Global.tsx
> +    // check referal
```suggestion
    // check referral
```

2024-08-13 20:25 UTC, michael1011 commented on src/utils/urlparams.ts
> +        resetUrlParam(param);
Why are we removing it?

2024-08-13 20:25 UTC, michael1011 commented on src/context/Global.tsx
> +        setHideHero(true);
Shouldn't that be an effect of `setEmbedded(true)`?

2024-08-13 20:25 UTC, michael1011 commented on src/context/Create.tsx
> +    // embed
You don't have to embed to use those

2024-08-13 20:25 UTC, michael1011 commented on src/context/Create.tsx
> +        assetSendParam !== assetReceiveParam
Why not just check if that pair is valid based on the API responses we fetch on load?

2024-08-13 20:25 UTC, michael1011 commented on src/context/Create.tsx
> +    // only set receive amount if send amount is set
```suggestion
    // only set receive amount if send amount is not set
```

2024-08-14 12:28 UTC, kilrau commented
Let's go @dni , @tohrxyz and team are waiting for this

2024-08-15 12:28 UTC, tohrxyz commented
I'm looking forward to have a few examples ready of URLs with different strategies for swaps. This will help also future devs with integrating with Boltz.

So far good job and I'm super happy with the responsiveness of you guys! :)

2024-08-16 16:21 UTC, maybeast approved these changes

2024-08-16 16:22 UTC, merged