fix: error on camera permissions denied
BoltzExchange/boltz-web-app pull request #635
Opened 2024-07-13 10:56 UTC by dni

closes #600

@kilrau translations

2024-07-14 16:20 UTC, michael1011 commented on src/i18n/i18n.ts
> +        error_starting_qr_scanner: "Error starting QR scanner",
How about asking to check the permissions?

2024-07-15 17:55 UTC, dni commented on src/i18n/i18n.ts
> +        error_starting_qr_scanner: "Error starting QR scanner",
```suggestion
        error_starting_qr_scanner: "Error starting QR scanner, check you camera permissions!",
```

2024-07-16 09:40 UTC, kilrau requested changes
Strings added and tested - looking good. What I do not like is that the "Scan QR Code" button disappears after a failed permissions. One has to refresh the site to get a new try. Just keep the button there please.
[Screencast from 07-16-2024 11:39:08 AM.webm](https://github.com/user-attachments/assets/9b476d8b-7d3d-4ee8-9a08-1c98b524dd56)

2024-07-23 07:34 UTC, dni commented
> Strings added and tested - looking good. What I do not like is that the "Scan QR Code" button disappears after a failed permission request. One has to refresh the site to get a new try. Just keep the button there please. [Screencast from 07-16-2024 11:39:08 AM.webm](https://github.com/user-attachments/assets/9b476d8b-7d3d-4ee8-9a08-1c98b524dd56)

done

2024-07-23 08:39 UTC, kilrau approved these changes
"Scan QR" button doesn't disappear now. Error comes up every time I press it. Behaves as expected.

2024-07-23 09:03 UTC, michael1011 approved these changes

2024-07-23 09:04 UTC, merged