RIF relay for claim transactions
BoltzExchange/boltz-web-app pull request #653
Opened 2024-07-29 21:55 UTC by michael1011

2024-08-01 10:15 UTC, kilrau commented
![image](https://github.com/user-attachments/assets/f290f9eb-dca2-442e-ab9f-568484ee3d2a)
liquid still not enabled

2024-08-01 10:18 UTC, michael1011 commented
> ![image](https://private-user-images.githubusercontent.com/19181985/354183054-f290f9eb-dca2-442e-ab9f-568484ee3d2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDc3MzEsIm5iZiI6MTcyMjUwNzQzMSwicGF0aCI6Ii8xOTE4MTk4NS8zNTQxODMwNTQtZjI5MGY5ZWItZGNhMi00NDJlLWFiOWYtNTY4NDg0ZWUzZDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDEwMTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkOWQyNjZjOGZkOGExZWU2MmExY2QwODM5YzgwYzBhNDAwNTM5MDIxZTVlMWZhMTgzYTFiMDYxODAxOWNjZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WE9Lg1fsbpodot7uP7n9j2c8xPUAiUDAp4Qw7rrp2XA) liquid still not enabled

Completely unrelated to the PR

2024-08-01 14:07 UTC, kilrau approved these changes
UA Tested

2024-08-03 20:07 UTC, maybeast reviewed
concept ACK

2024-08-03 20:07 UTC, maybeast commented on src/components/CreateButton.tsx
> +            const balanceNeeded = gasPrice * GasNeededToClaim;
when deploying for the first time should we also account for `GasNeededToDeploy` here?

2024-08-09 12:08 UTC, kilrau requested changes
EDIT: fixed on latest commit

2024-08-09 12:36 UTC, kilrau commented
Starting to look good!!

2024-08-12 16:48 UTC, maybeast approved these changes

2024-08-15 11:07 UTC, merged