feat: validate invoices fetched for offers
BoltzExchange/boltz-web-app pull request #706
Opened 2024-10-22 18:20 UTC by michael1011

2024-10-22 19:21 UTC, maybeast commented on src/utils/invoice.ts
> +            console.log("no match");
remove or add more context. In the current state it's pretty useless.

2024-10-22 19:21 UTC, maybeast commented on src/utils/invoice.ts
> +        for (const hop of hops) {
```suggestion
        hops.forEach(hop => hop.free());
```

2024-10-22 19:31 UTC, maybeast approved these changes

2024-10-23 11:10 UTC, kilrau commented
2/10 of my testnet bip353 resolve tests needed too long to wake up my phoenix app. Happened when I restarted my phone to make sure Phoenix is not running in the background already. But the notification literally came in a second or two after web app timed out with "failed to fetch". I suggest to bump the timeout for about 3s.

2024-10-23 11:14 UTC, kilrau requested changes
Refund qr code generation fails (json works). Also we should throw a tool tip error if that happens and block the jump to the next screen to not let users create swaps without refund file.

![image](https://github.com/user-attachments/assets/eded8d47-c592-4705-8c1e-ca91ca2e78e6)

2024-10-23 11:51 UTC, kilrau approved these changes
Moved above comments into separate issues. Invoice <> Offer validation works.

2024-10-23 11:53 UTC, merged