feat: 0-amount chain swaps
BoltzExchange/boltz-web-app pull request #741
Opened 2024-11-15 11:35 UTC by michael1011

Closes #719

@kilrau needs translations

2024-11-19 19:02 UTC, jackstar12 commented on src/components/PayOnchain.tsx
> +        if (pairs() !== undefined) {
Why not use `fetchPairs` from the global context here?
https://github.com/BoltzExchange/boltz-web-app/blob/8f6e924dc88a23d0fb33b016978acda5d6daf5bf/src/context/Global.tsx#L78

2024-11-20 14:39 UTC, kilrau requested changes
When I actually sent coins (which took maybe 2 minutes because of me screenshotting and testnet3 being testnet3): I got a new quote combined with an error message. This state shouldn't exist. Either I get a new quote or Lockup failed.

![Screenshot from 2024-11-20 15-32-46](https://github.com/user-attachments/assets/455109fc-35dd-46b6-891a-d14c90eb2552)

Now when I "Accepted" the new quote it turns out the lockup actually failed. Still something missing on backend side?

![image](https://github.com/user-attachments/assets/eb503ed1-334a-42c1-862b-4a4c6514dd2b)


Tested my strings, checks out:
![Screenshot from 2024-11-20 15-29-13](https://github.com/user-attachments/assets/6d28a253-47c5-4047-937b-4e8c3aed7fa4)
![Screenshot from 2024-11-20 15-28-45](https://github.com/user-attachments/assets/0d9016f4-fe5d-489c-a64e-09dfd2d56bff)
![Screenshot from 2024-11-20 15-28-35](https://github.com/user-attachments/assets/bfe4aa77-75e4-4b46-b8e7-9396a76a9417)
![Screenshot from 2024-11-20 15-28-26](https://github.com/user-attachments/assets/ed8353c4-c070-4ab5-8ec8-75dcaa4138b9)
![Screenshot from 2024-11-20 15-28-21](https://github.com/user-attachments/assets/1d6868f5-4601-43f0-9eba-2905f0e45afc)

2024-11-27 11:20 UTC, jackstar12 commented
New styling:
![image](https://github.com/user-attachments/assets/99eca3e4-391b-49f5-9315-ed90f374cac1)

2024-11-27 15:30 UTC, kilrau commented
Strings pushed, please check tests

2024-11-27 16:20 UTC, merged