feat: add chatwoot, replace discord as main help link
BoltzExchange/boltz-web-app pull request #745
Opened 2024-11-25 15:34 UTC by kilrau

2024-11-25 15:46 UTC, michael1011 requested changes
The Chatwoot script should be loaded programmatically in the entrypoint of the Solid application *if* its token is set in the `.env` file

2024-11-25 15:46 UTC, michael1011 commented on index.html
> +                var BASE_URL="https://support.boltz.exchange";
Should be configurable

2024-11-25 15:46 UTC, michael1011 commented on index.html
> +                    websiteToken: 'poETNyKsWeqUqB9M9QYGJHKT',
Tokens should ***never*** be committed. These go into the `.env` file

2024-11-25 15:46 UTC, michael1011 requested changes
GitHub posted the review twice

2024-11-27 15:49 UTC, kilrau commented
Can't approve as it's my own PR, but LGTM

2024-11-27 17:03 UTC, michael1011 requested changes

2024-11-27 17:03 UTC, michael1011 commented on src/chatwoot.ts
> +                swapId: swap().id,
Is not propagated to the Chatwoot UI

2024-11-27 17:06 UTC, michael1011 commented on src/chatwoot.ts
> +        if (token !== undefined && url !== undefined) {
Let's also do a `log.warn` in case it's not set

2024-11-28 07:44 UTC, merged